# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to docker
      inputs:
        containerRegistry: 'docker-hub-somphouang'
        command: 'login'
    - task: Docker@2
      displayName: Build and push
      inputs:
        containerRegistry: 'docker-hub-somphouang'
        repository: 'somphouang/norconex-devops-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

