apiVersion: v1
kind: Service
metadata:
  name: {{ include "norconex-devops-demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "norconex-devops-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
  selector:
    {{- include "norconex-devops-demo.selectorLabels" . | nindent 4 }}
